### ISSUE TITLE
Error using Distributed Cache Dependency 3.2.5 when 3.3.0 DependencyInjection is installed

### ISSUE THREAD

**Issue by Simba-Mupfunya** [couchbaselabs/Couchbase.Extensions#102]
System.IO.FileNotFoundException: 'Could not load file or assembly 'Couchbase.Extensions.DependencyInjection, Version=3.2.5.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2'. The system cannot find the file specified

"Couchbase.Extensions.Caching.CouchbaseCacheServiceCollectionExtensions.AddDistributedCouchbaseCache(IServiceCollection services, string bucketName, Action<CouchbaseCacheOptions> setupAction)"

**Comment by jeffrymorris** [comment]
@Simba-Mupfunya 

It looks like packaging issue in versions 3.2.7 to 3.3.0 where the assembly version is being set to 3.0.1.0 which is a default in the scripts. Thanks for reporting, we will push 3.3.1 up shortly with the proper assembly version.

Jeff

**Comment by Simba-Mupfunya** [comment]
any news? i still dont see an update to the package

**Comment by jeffrymorris** [comment]
@Simba-Mupfunya 

It should be up, but looks like the publishing step in the build pipeline failed.

**Comment by jeffrymorris** [comment]
This has been resolved.
