### ISSUE TITLE
reloadOnChange

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/Couchbase.Extensions#12]
It doesn't seem like making a change to appsettings.json causes Couchbase config to reload, even though `reloadOnChange` is true. I think this might be because `IOptions` is used in https://github.com/couchbaselabs/Couchbase.Extensions/blob/master/src/Couchbase.Extensions.DependencyInjection/Internal/ClusterProvider.cs instead of `IOptionSnapshot`.

Is this intentional? Would `IOptionSnapshot` not work correctly? Stuff like 'adding nodes to a cluster' might not happen terribly often, but it might be nice not to have to restart the app if I did have to do that.

**Comment by brantburnett** [comment]
I'm not sure how well the main Couchbase SDK can handle having its configuration reloaded while it's live and operational.  I'd think we'd have to close the ICluster and open a new one.  But maybe that could be done in a rollover manner.

@jeffrymorris any input on this?

**Comment by jeffrymorris** [comment]
@brantburnett @mgroves -

To do this you would have to close/dispose of the Cluster and buckets that are open and re-initialize everything.

> Stuff like 'adding nodes to a cluster' might not happen terribly often, but it might be nice not to have to restart the app if I did have to do that.

Adding node to a cluster is handled internally via communication between the server and the client. The client configuration does not need to be updated manually from the apps perspective - it "just works".

-Jeff

**Comment by mgroves** [comment]
@jeffrymorris I meant adding nodes to appsettings.json - I know it will "just work", except in the case (probably rare, which is why this might be a nice to have) where e.g. nodes A,B,C,D in a cluster, A,B are in the config, A,B are down, C,D are still up, the app wouldn't know how to find the cluster until you add C,D to config and then restart the app. But instead of a restart, a 'reloadOnChange' trigger would be better (I think).

**Comment by jeffrymorris** [comment]
@mgroves -

Nodes C,D would have been added to the configuration at runtime when the cluster map is updated. Assuming that all nodes are part of the same cluster. You can start with a single endpoint in  the config and rebalance it out and the app will continue to function; if you tried to re-bootstrap with the node that is no longer a member of the cluster, the client would actually be able to use it assuming it's online. 

-Jeff
