### ISSUE TITLE
Couchbase.Extensions.Lock Moving Out of Beta

### ISSUE THREAD

**Issue by RichCerone** [couchbaselabs/Couchbase.Extensions#65]
Hello, I have been using the Couchbase.Extensions.Lock package and noticed that it has been in a pre-release version in nuget for quiet a while. Is there any plan to move this to an official release? Is this planned to be supported for future releases of Couchbase as well?

**Comment by brantburnett** [comment]
I actually just noticed this myself today. We've been using it in production for several months, it's probably time to make version 1.0.0. @jeffrymorris is that something you can do?

**Comment by MikeGoldsmith** [comment]
If there aren't any changes required, I can publish a 1.0 tomorrow.

**Comment by RichCerone** [comment]
Any updates on this going to 1.0?

**Comment by RichCerone** [comment]
Hey @MikeGoldsmith, just checking up again to see if any progress was made.

**Comment by MikeGoldsmith** [comment]
I tried to do the release today but due to a permissions issue I wasn't able to upload to nuget.org. We'll work on getting that fixed ASAP.

Sorry again for the delay.

**Comment by RichCerone** [comment]
@MikeGoldsmith any updates on this still?

**Comment by MikeGoldsmith** [comment]
I do not currently have permission to upload the package to Nuget. I have escalated to someone who does but haven't heard back. I'll chase them again.

**Comment by brantburnett** [comment]
@RichCerone In the interim, I've put a version 1.0.0 on our private MyGet servers so that we could use it internally. If you want to do the same, I can send you the .nupkg file.

**Comment by jeffrymorris** [comment]
@RichCerone - 

1.0.0 has been published to NuGet: https://www.nuget.org/packages/Couchbase.Extensions.Locks/1.0.0

Thanks for your patience!

-Jeff/Mike
