### ISSUE TITLE
Not compatible with CouchbaseNetClient 2.7.14

### ISSUE THREAD

**Issue by mtinnes** [couchbaselabs/Couchbase.Extensions#68]
After upgrading to the latest Couchbase .NET client we are getting the following error indicating a dependency on an older version of the library:

`Error	CS0012	The type 'IBucket' is defined in an assembly that is not referenced. You must add a reference to assembly 'Couchbase.NetClient, Version=2.5.9.0, Culture=neutral, PublicKeyToken=05e9c6b5a9ec94c2'.	RevelDigital.Core.PublicApi`

**Comment by jeffrymorris** [comment]
@mtinnes -

I think the issue is that 2.7.14 is missing the signing key; I'll push another package today. Would you mind validating that this resolves the issue for you before I push the package?

-Jeff

**Comment by jeffrymorris** [comment]
@mtinnes -

I pushed https://www.nuget.org/packages/CouchbaseNetClient/2.7.15.  Let me know if you have any additional issues.

Thanks,

-Jeff
