### ISSUE TITLE
Upgrade to Couchbase .NET SDK 3.0 GA

### ISSUE THREAD

**Issue by mgroves** [couchbaselabs/Couchbase.Extensions#70]
I'm able to reproduce the issue opened in this StackOverflow question - https://stackoverflow.com/questions/61311832/net-core-project-is-getting-error-while-using-couchbasenetclient-3-0-0-package

It seems to be caused by installing SDK 3.0 and then installing the Dependency Injection package.

How big of an effort would it be to get at least the DI package updated to work with 3.0?

**Comment by brantburnett** [comment]
@mgroves There is a "new" version of the DI package in the main "couchbase-net-client" repo, already updated for compatibility. The decision was made to make this an official part of the SDK and version it together with the SDK. 

It just needs to be built and deployed to NuGet (which I don't have permissions to do). In the meantime, it could be built and used directly from there as a workaround.

https://github.com/couchbase/couchbase-net-client/tree/master/src/Couchbase.Extensions.DependencyInjection

**Comment by mgroves** [comment]
@brantburnett do you know if there's an NCBC on issues.couchbase.com for this? I don't see one, but wanted to double check. I want to make it easier for @jeffrymorris and create one if there isn't already

**Comment by brantburnett** [comment]
@mgroves Not to my knowledge, no

**Comment by mgroves** [comment]
Thanks @brantburnett I just created one: https://issues.couchbase.com/browse/NCBC-2464

**Comment by jeffrymorris** [comment]
Closed because DI and DNS-SRV is part of the github.com/couchbase/couchbase-net-client, but reopening because the other extensions are still part of this repo and DNS-SRV for sdk2 is still a separate project.
