### ISSUE TITLE
.Net Framework version?

### ISSUE THREAD

**Issue by bVanHertum** [couchbaselabs/Couchbase.Extensions#71]
Hello,

Small question: I know the description on this project says .Net Core, but considering the Couchbase .Net Client also supports it, is there any chance you'd also publish a .Net Framework version?

Thanks,

Bert

**Comment by brantburnett** [comment]
@bVanHertum which specific project are you referring to?

**Comment by bVanHertum** [comment]
Couchbase.Extensions.Locks in this case. I'm trying to get rid of a custom-built mutex solution we're currently using. Considering the dependencies, I don't think a .Net Framework version should cause any issues - in the process of doing a local test, myself.

**Comment by brantburnett** [comment]
@bVanHertum Actually, that package should be compatible with the .NET Framework 4.6.1 and later as-is. It targets .NET Standard 2.0, and doesn't use any .NET Core specific dependencies.

**Comment by bVanHertum** [comment]
It would... if we were on .Net Framework 4.6.1 at least - this project is still on 4.6, which is only compatible with .Net Standard up to 1.3 according to https://docs.microsoft.com/en-us/dotnet/standard/net-standard

OK, you can close this one. Looks like a Framework upgrade is in order.

**Comment by brantburnett** [comment]
@bVanHertum Okay, please let me know if you have any problems after the upgrade.
