### ISSUE TITLE
Comapitbility with Couchbase .NET SDK 3.0+

### ISSUE THREAD

**Issue by RichCerone** [couchbaselabs/Couchbase.Extensions#79]
Are these extensions compatible with the latest Couchbase .NET SDK? Sepcifically Couchbase.Extensions.Locks? We are looking to move our Couchbase SDK from 2.7.x to 3.0.x

**Comment by brantburnett** [comment]
The DependencyInjection extension has been moved to the main SDK repo for 3.x, and is compatible. However, none of the other extensions have been ported yet.

**Comment by RichCerone** [comment]
Okay, thank you! Do you have any estimate on when the rest of the extensions will be ported over? I believe EOL for SDK 2.7 is December 2020.

**Comment by kaiohenrique** [comment]
Any news about that upgrade?

**Comment by brantburnett** [comment]
@RichCerone @kaiohenrique 

I milestone has been created for this migration: https://github.com/couchbaselabs/Couchbase.Extensions/milestone/1

There is a specific issue for Locks: #83 

The work on Locks is in progress, you can actually build from source and use it now: https://github.com/couchbaselabs/Couchbase.Extensions/tree/locks-3x

**Comment by brantburnett** [comment]
I'm closing this issue for now, going forward it can be monitored via the milestone.
