### ISSUE TITLE
Distributed Cache and Ephemeral Bucket

### ISSUE THREAD

**Issue by kaiohenrique** [couchbaselabs/Couchbase.Extensions#80]
I have seem that Distributed Cache extension does not mention Ephemeral but I was able to use it with ephemeral bucket without problems. Am I missing something? 
Also, do we have any estimation when Couchbase SDK 3.0+ will be integrated to extensions?

**Comment by mgroves** [comment]
Hi @kaiohenrique, I don't think using an Ephemeral bucket would be a problem for distributed cache. Makes sense to me :)

As for SDK 3 in extensions, I can tell that you that the DependencyInjection extension has already been updated and is now in the official .NET SDK repo here: https://github.com/couchbase/couchbase-net-client (but I don't know about the other extensions)

**Comment by kaiohenrique** [comment]
But, @mgroves, Is there any limitation to use Ephemeral bucket through Distributed Cache extension? Or is it compatible with Ephemeral and Couchbase?

**Comment by mgroves** [comment]
I don't see why it wouldn't work for both. Did you have something in mind? A particular issue you're concerned about?

**Comment by kaiohenrique** [comment]
Actually not, @mgroves . It is just to be sure! As documentation wasn't explicitly mentioning ephemeral bucket I got doubtful, was afraid I was going on the wrong way. Perfect then. Thank you! 😄

**Comment by brantburnett** [comment]
Yes, distributed cache is compatible with Ephemeral buckets. In fact, for most use cases I would recommend Ephemeral buckets. They basically support everything a full persisted bucket can do, except they don't write to disk. There may be a couple of limitations around N1QL queries in community edition, I'm not sure if those still apply, but mostly they do everything.
