### ISSUE TITLE
Update Sessions for SDK 3.x

### ISSUE THREAD

**Issue by brantburnett** [couchbaselabs/Couchbase.Extensions#85]
Blocked by #84

**Comment by RichCerone** [comment]
Any update on when the sessions extension library will be on SDK 3.0?

**Comment by jeffrymorris** [comment]
@RichCerone - Its in progress atm; converting over the unit tests is proving to be time consuming!

-Jeff

**Comment by RichCerone** [comment]
Great! Thanks for the update!

**Comment by RichCerone** [comment]
Any update on this? It is getting close to EOL for Couchbase 2.x SDK.

**Comment by jeffrymorris** [comment]
Session 3.3.5 is up on nuget: https://www.nuget.org/packages/Couchbase.Extensions.Session/3.3.5
