### ISSUE TITLE
[Question] CarrierPublication or HttpStreaming?

### ISSUE THREAD

**Issue by kaiohenrique** [couchbaselabs/Couchbase.Extensions#89]
Hey, guys.
I couldn't find any resource in the Couchbase documentation to help me understand which ConfigurationProviders to use. 
Are there any rule of thumb?
We plan to deploy an Ephemeral Bucket for cache purposes.

**Comment by brantburnett** [comment]
Under most circumstances, you should leave it at the default, which is to have both enabled. It will try to connect with CCCP (the more modern protocol) and fallback to HTTP if that doesn't work. There are some very special circumstances where you may want to disable CCCP, but those are pretty unusual advanced use cases.
