### ISSUE TITLE
Question regarding the documentation -- docs/dependency-injection.md

### ISSUE THREAD

**Issue by ToMakeSense** [couchbaselabs/Couchbase.Extensions#96]
You mentioned `Couchbase.Extensions.DependencyInjection` had been **relocated**,  does the **relocated** just means version aligned with main SDK? I can't find the `Couchbase.Extensions.DependencyInjection` namespace in `CouchbaseNetClient` library.

---
:warning: **Note:** Couchbase.Extensions.DependencyInjection has been relocated to [the main SDK repository](https://github.com/couchbase/couchbase-net-client) for SDK 3.x, and is now versioned alongside the SDK.

For documentation related to SDK 3.x, see the [official documentation](https://docs.couchbase.com/dotnet-sdk/3.0/howtos/managing-connections.html#connection-di).

For documentation related to SDK 2.x, see the [sdk2x branch](https://github.com/couchbaselabs/Couchbase.Extensions/blob/sdk2x/docs/dependency-injection.md).

---

**Comment by ToMakeSense** [comment]
I also got confused after referring to the [official documentation](https://docs.couchbase.com/dotnet-sdk/3.0/howtos/managing-connections.html#connection-di), I just can't get **DependencyInjection** working on .net core 3.1.

For simple get & set document in bucket, if using [Couchbase.Extensions.Caching](https://www.nuget.org/packages/Couchbase.Extensions.Caching/), it's easy as it's described in the [caching.md](https://github.com/couchbaselabs/Couchbase.Extensions/blob/master/docs/caching.md) 
```csharp

// set
_cache.SetAsync("CacheTime", System.Text.Encoding.UTF8.GetBytes(DateTime.Now.ToString()));

// get
_cache.Get("CacheTime")
```

But how to make it with [Couchbase.Extensions.DependencyInjection](https://www.nuget.org/packages/Couchbase.Extensions.DependencyInjection/)? the official docs add simple example with **//do some work**, it's no help...
```csharp
    public async Task<IActionResult> IndexAsync()
    {
        var bucket = await _provider.GetBucketAsync();
        //do some work

        return View();
    }
```

**Comment by brantburnett** [comment]
> You mentioned `Couchbase.Extensions.DependencyInjection` had been **relocated**, does the **relocated** just means version aligned with main SDK? I can't find the `Couchbase.Extensions.DependencyInjection` namespace in `CouchbaseNetClient` library.
> 
> ⚠️ **Note:** Couchbase.Extensions.DependencyInjection has been relocated to [the main SDK repository](https://github.com/couchbase/couchbase-net-client) for SDK 3.x, and is now versioned alongside the SDK.
> 
> For documentation related to SDK 3.x, see the [official documentation](https://docs.couchbase.com/dotnet-sdk/3.0/howtos/managing-connections.html#connection-di).
> 
> For documentation related to SDK 2.x, see the [sdk2x branch](https://github.com/couchbaselabs/Couchbase.Extensions/blob/sdk2x/docs/dependency-injection.md).

@ToMakeSense 

The source code for 3.x has been relocated to the main SDK repository. However, it is still a separate NuGet package that is version-aligned.

https://github.com/couchbase/couchbase-net-client/tree/master/src/Couchbase.Extensions.DependencyInjection

As to using the bucket, the example you showed was for using DI to get the bucket itself. There is other documentation on how to use the bucket/collection/scope to work with documents.

https://docs.couchbase.com/dotnet-sdk/current/howtos/kv-operations.html

Typically it may be something like this:

```cs
public async Task<IActionResult> IndexAsync()
    {
        var bucket = await _provider.GetBucketAsync();

        var collection = bucket.DefaultCollection();

        var document = await collection.GetAsync<DocType>("doc-key");

        return View();
    }
```

**Comment by ToMakeSense** [comment]
@brantburnett Thanks for your clarification.
